services:
  ctour:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./node_modules:/usr/src/nuxt-app/node_modules
      - ./.nuxt/:/usr/src/nuxt-app/.nuxt
      - .:/usr/src/nuxt-app
    depends_on:
      - db
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    command: sh -c " npx prisma migrate dev --name init && npx prisma db seed && npm run dev"
  db:
    build:
      context: ./postgreExtendedImage
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 503553Danil2030
      POSTGRES_DB: cinemaTour
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  meilisearch:
    build:
      context: .
      dockerfile: meilisearchDockerfile
    restart: always
    ports:
      - 7700:7700
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - ./meilisearch_data:/meilisearch_data
  meilisync:
    build:
      context: .
      dockerfile: meilisyncDockerfile
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - ./config.yml:/meilisync/config.yml
    command: sh -c " python3 -m meilisync_config_keygen --address http://meilisearch:7700 --path config.yml && meilisync start"

volumes:
  postgres_data:
