debug: true
meilisearch:
  api_key: cf4e8f72aee5681ec574a06570c5fbb846edec8390e3e9882e17cf86b54d8074
  api_url: http://meilisearch:7700
  insert_interval: 10
  insert_size: 1000
progress:
  type: file
source:
  database: cinemaTour
  host: db
  password: 503553Danil2030
  port: 5432
  type: postgres
  user: postgres
sync:
- full: true
  table: film
- full: true
  table: stuff
- full: true
  table: country
- full: true
  table: selection
- full: true
  table: voicestudio
- full: true
  table: genre
