debug: true
meilisearch:
  api_key: 211a6f102ead2d89471cd532067446c9f50040deaeddcdcb4903de49e7c6cadf
  api_url: http://meilisearch:7700
  insert_interval: 10
  insert_size: 1000
progress:
  type: file
source:
  database: cinemaTour
  host: db
  password: 503553Danil2030
  port: 5432
  type: postgres
  user: postgres
sync:
- full: true
  table: film
