debug: true
meilisearch:
  api_key: 0339d6c4056f0fae7afc89690983cbccd792002e5e6cd45577840d9874b6d2d0
  api_url: http://meilisearch:7700
  insert_interval: 10
  insert_size: 1000
progress:
  type: file
source:
  database: cinemaTour
  host: db
  password: 503553Danil2030
  port: 5432
  type: postgres
  user: postgres
sync:
- full: true
  table: film
